#!/bin/bash
# Run inside a Docker container

export PGPASSWORD=$PLOTLY_DB_PASSWORD
export DATABASE_URL="postgresql://$PLOTLY_DB_USER@$PLOTLY_DB_HOST/dashboardsly"
PSQL="psql -U $PLOTLY_DB_USER -h $PLOTLY_DB_HOST"

cd /opt/dashboardsly

echo Waiting for database...
while true ; do
    $PSQL db1 -w -c "SELECT 1" && {
        break
    }
    sleep 1
done

if ! $PSQL -lqt | cut -d \| -f 1 | grep -w dashboardsly; then
    echo DB does not exist
    $PSQL db1 -c 'CREATE DATABASE dashboardsly;'
else
    echo DB exists
fi

python init_db.py

gunicorn runserver:app --log-file=- -b 0.0.0.0:80
